from setuptools import setup

setup(
        name='CompositeView', 
        version='1.1.0', 
        description='A package for visualizing composite score data',
	author='Stephen Allegri',
	author_email='sallegri3@gatech.edu',
	packages=['composite_view'],
	install_requires=[
                'Brotli==1.0.9', 
                'click==8.1.2', 
                'colorama==0.4.4', 
                'colour==0.1.5', 
                'dash==2.0.0', 
                'dash-bootstrap-components==1.0.1', 
                'dash-core-components==2.0.0', 
                'dash-cytoscape==0.2.0', 
                'dash-html-components==2.0.0', 
                'dash-table==5.0.0', 
                'Flask==2.1.1', 
                'Flask-Compress==1.11', 
                'importlib-metadata==4.11.3', 
                'itsdangerous==2.1.2', 
                'Jinja2==3.1.1', 
                'joblib==1.1.0', 
                'MarkupSafe==2.1.1', 
                'networkx==2.6.3', 
                'numpy==1.22.3', 
                'pandas==1.4.2', 
                'plotly==5.7.0', 
                'python-dateutil==2.8.2', 
                'pytz==2022.1', 
                'scikit-learn==1.0.2', 
                'scipy==1.8.0', 
                'six==1.16.0', 
                'tenacity==8.0.1', 
                'threadpoolctl==3.1.0', 
                'Werkzeug==2.0.1', 
                'zipp==3.8.0'
                ]
)